[package]
authors = ["Joshua Barretto <joshua.s.barretto@gmail.com>", "Imbris <imbrisf@gmail.com>"]
edition = "2021"
name = "veloren-voxygen-anim"
version = "0.10.0"

[features]
use-dyn-lib = ["lazy_static", "common-dynlib"]
be-dyn-lib = []
simd = ["vek/platform_intrinsics"]

default = ["simd"]

[dependencies]
common = {package = "veloren-common", path = "../../common"}
bytemuck = { version = "1.4", features=["derive"] }
vek = { workspace = true }
common-dynlib = {package = "veloren-common-dynlib", path = "../../common/dynlib", optional = true}
inline_tweak = { workspace = true, features = ["derive"] }

# Hot Reloading
lazy_static = { workspace = true, optional = true}
